### PR TITLE
Fix copyright infrigement

### PR DESCRIPTION
**Pull request by loblao**
This repository contains my gardening code, without my consent. I'm politely requesting its removal in order to prevent me from filling a DMCA form.

### CODE REVIEW

**Comment by Loudrob** [comment]
:+1:

**Comment by Spiderlover** [comment]
Um, the code belongs to Disney. It's against copyright laws to copyright Disney's work under your name.

**Comment by loblao** [comment]
I wrote those AIs myself.

**Comment by pslifeisgood** [comment]
+1 

p.s @Spiderlover if you want to engage in copyright laws with us, we can definitely have that conversation, but I can assure you that it will not be working out in your favor as you are also running lines of my code.

**Comment by Spiderlover** [comment]
Yeah, but the code owner is still Disney, since they still own copyright for Toontown and the code.

**Comment by pslifeisgood** [comment]
@Spiderlover Again, no. Disney did not publicize their AIs, these belong to nacib

**Comment by Spiderlover** [comment]
Ok

**Pull request merged**
